### ISSUE TITLE
the pokemon to evolve bug

### ISSUE THREAD

**Issue by sunit1998** [Ar1i/PokemonGo-Bot#1009]
everytime i restart the bot the pokemons to evolve changes and makes the other pokemons to evolve please fix this error

**Comment by UltraVLT** [comment]
Do you have a config folder with text files that have your settings saved? Normally if you do,it should save it. Also don't forget to unpack the rar otherwise he can't write the set files.

**Comment by FrancYescO** [comment]
Confirming this issue, pretty strange.

**Comment by Zarroc15** [comment]
In the last commit [https://github.com/Ar1i/PokemonGo-Bot/commit/e3d55678319f880a60e8fb3403a5df580b7149dd](url) the Sorted property of the three CheckListBoxes (Transfer, Catch, Evolve) in the GUI was set to true, which messes with the algorithm for reading the saved settings and checking the checkboxes because the ids of the boxes are not in sync with the Pokemon Ids anymore. The result are wrong settings in the GUI which will be saved when you click 'save config'.

**Comment by gise88** [comment]
Hmmm! I didn't see this issue.. :unamused: I just opened this related https://github.com/Ar1i/PokemonGo-Bot/issues/1056
