### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Syzen** [Ar1i/PokemonGo-Bot#1041]
Muss man immer alles neu downloaden wegen Updates, oder gibt es eine Möglichkeit selbst die Updates zu machen ?

**Comment by elenex23** [comment]
For new updates you need to download zip and put all of the contents into new folder. Save older versions in a folder and only use brand new ones.

**Comment by mridhoe** [comment]
so we must use brand new one right ? how about old version delete it or just keep it ?

**Comment by elenex23** [comment]
I save ever bot and version I've used in my "old bots" folder. You never
know when you need the old logs

On Aug 2, 2016 5:28 PM, "mridhoe" <notifications@github.com> wrote:

so we must use brand new one right ? how about old version delete it or
just keep it ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Ar1i/PokemonGo-Bot/issues/1041#issuecomment-237093227>,
or mute the thread

**Comment by xJustx** [comment]
Du musst nicht zwingend Updaten. Du kannst natürlich auch selber am Source rumbasteln.
Wenn du ein Update lädst kannst du deine Configs behalten, indem du den Config-Ordner mit nimmst. 

====

You must not download always the newest version. If you want you can edit the source yourself.
If you download a update and you want to keep your configs so you copy and paste your config-folder into the "new bot".
