### ISSUE TITLE
Is this a problem with the coding or Niantic preventing cheating

### ISSUE THREAD

**Issue by matts829** [Ar1i/PokemonGo-Bot#1357]
Does anybody know because if non of the bots work than I imagine niantic is cracking down on cheating and is changing their coding to prevent it

**Comment by spena1024** [comment]
go away!!!

**Comment by spena1024** [comment]
you opened a new thread for this stupid question?

**Comment by matts829** [comment]
@spena1024 Ok Number 1 you dont have to be a fucking cunt. Second of all if your so smart answer the damn qustion

**Comment by spena1024** [comment]
let me call niantic and ask him! wait nvm its not relevant point is it doesnt work and your filling Ar1i issues with new threads asking dumb ass questions. AMAZING!!!

**Comment by Biscuit090** [comment]
People like you who don't read previous threads that say "READ ME BEFORE POSTING" are the new definition of AIDS. Just please stop asking these stupid questions that you obviously know the answer to. And if you haven't figured it out, yes, Niantic has been cracking down on cheating ever since they released the game! That's why soft bans are so common.

**Comment by wreckoning** [comment]
@matts829 

TBH you deserve all the shit you're getting. You obviously just joined to know why your beloved bot does not work and never really bothered to read the million other fucking threads explaining whats happening.

SERIOUSLY if cancer can spread through the internet, you'd be patient zero.

**Comment by Ozymumbles1** [comment]
@matts829 Maybe you should learn to read other threads, that would be a smart thing to do.

**Comment by Bannz** [comment]
ROTFL.. chill everyone... he just wake up with left bot on his pc.
