### ISSUE TITLE
Just Wait.....

### ISSUE THREAD

**Issue by FerMedina86** [Ar1i/PokemonGo-Bot#1409]
![cod](https://cloud.githubusercontent.com/assets/20867022/17452155/41364582-5b32-11e6-8329-1fca2035d4f8.jpg)

**Comment by 0x92** [comment]
Can someone verify it?

**Comment by Zuldar** [comment]
"I AM NOT OFFICIAL PokemongoDev Reddit" in description.....

**Comment by darkoroty** [comment]
say is not account official for pokemon, or niantics :l

**Comment by FerMedina86** [comment]
https://twitter.com/RedditPokeGoDev

**Comment by Zuldar** [comment]
nothing here. https://www.reddit.com/live/xdkgkncepvcq/

**Comment by pokerave** [comment]
![pokemongodev](https://cloud.githubusercontent.com/assets/20603254/17452319/e520dc90-5b76-11e6-9136-e0eec786e113.jpg)

**Comment by pokerave** [comment]
redditpokegodev guys are just informing Niantic about the development

**Comment by Waiiim** [comment]
Not the smartest move, if they don't want another update in the coming week lol

**Comment by Correexx** [comment]
the guy who said he had the result earlier just had that: 
class NetflixAPIError(Exception): pass
class NetflixAuthError(NetflixAPIError): pass
and 
"HEY POKEGO CHEATERS,


FUCK YOUR MOTHERS YOU PEICE OF SHIT. GET OUT IN THE SUN AND HUNT POKEMON INSTEAD OF CHEATING."

xD best guy i think :)

**Comment by Leak1337** [comment]
This Readme from him haha:


Gotcha! LoL

You fucking cheating scumbags. You business ruining bunch of useless runts.
Reddit pokemongo dev especially consists of great mixture of wankers, faggots and copycat losers.
Get a life you sad pricks, why dont u get your fucking fat ass out in the wild and play the game.

I hope you will never be able to crack the unknown6 decryption, and if you do I hope Niantic swiftly implements a new one so you
have to do it all over again. Go Niantic, kill these business-ruining runts.

"3 steptracker not working"
"I only get zubats without the map"
HOW ABOUT YOU SHUT UR GAYMOUTH BEFORE I BOX YOUR FACE IN xD

Let Niantic fix the bugs, let Niantic solve the tracking issues. 

But no, always have to cheat. Is it because you are a bunch of sad pathetic rejects in life? =)

You may have destroyed my business by exploiting the game but I sure am not going to bat an eyelid everytime I see you squirm on reddit about bots not working LOL

Have fun suckers

https://twitter.com/mofo

**Comment by Waiiim** [comment]
1- Who the **** is mofo
2- Haters gonna Hate
3- He clearly has complexes to talk smack like that

**Comment by UraharaKisuke07** [comment]
It's so hilarious to watch those level 12 guys salty like that
