### ISSUE TITLE
does it work now?

### ISSUE THREAD

**Issue by razor3003** [Ar1i/PokemonGo-Bot#1437]

**Comment by HeIIoWorld** [comment]
No

**Comment by razor3003** [comment]
OK THANKS

**Comment by Biscuit090** [comment]
Can we stop asking stupid questions?

**Comment by CreativiTimothy** [comment]
Creating a new issue is to make a detailed document of a bug. It's not a chatroom

**Comment by pokerave** [comment]
I have monitored everything since day one of the unknown6, i think they are close to breaking it or even cracked it. they have close the reddit, ownedcore, pokemongodev, etc site, another bot maker said they are making a test bot to see. SO JUST BE PATIENT...

![close](https://cloud.githubusercontent.com/assets/20603254/17459189/21fd77f2-5c37-11e6-80d5-99b2de97a049.jpg)

**Comment by ZombiePm** [comment]
why you dont try this https://github.com/AHAAAAAAA/PokemonGo-Map/

**Comment by Jadijee** [comment]
come on.. can you just read something from here and stop making a new issue

**Comment by momo0206** [comment]
@ZombiePM the map does'nt work

**Comment by Keyabuza** [comment]
Are you guys dumb or what ?

**Comment by xJustx** [comment]
^
