### ISSUE TITLE
New API is really working, first Bot starts to work again.

### ISSUE THREAD

**Issue by lailaps** [Ar1i/PokemonGo-Bot#1450]
:)

**Comment by WalkingResurrector** [comment]
What?

**Comment by rbarrantes** [comment]
What x2 ?

**Comment by Ted0504** [comment]
What x3 ?

**Comment by WalkingResurrector** [comment]
^^^^^^^^^^^^^^

**Comment by Biscuit090** [comment]
Pokefarmer.com is currently one of the only bots working at the moment. There are some issues with the bot such as having to restart it every 20 minutes but it does work so try it out until the official one is released by Ar1i.

**Comment by WalkingResurrector** [comment]
@Biscuit090 ew

**Comment by TheShade1337** [comment]
Nah, I am faithful to Ar1i :D

**Comment by WalkingResurrector** [comment]
^

**Comment by Georgiexoh** [comment]
^^

**Comment by peoplearmy** [comment]
@Biscuit090 Pokefarmer is not free and is subscription based meaning you pay it monthly.  Anyone who pays for that bot risks buying a bot that may become useless if Niantic changes their API's again. Since pokefarmer does not own the Niantic API's they can't guanrantee that their product will remain valid.  Please be patient and wait for @Ar1i or if you must have a working bot the you can try compiling this free python based [bot](https://github.com/PokemonGoF/PokemonGo-Bot) and use it till this one is working.

**Comment by Midnlght** [comment]
yeah i wouldn't use any other bot but Ar1i, its the only one I trust/ like lol

**Comment by alchem9st** [comment]
Coool can't wait :P

**Comment by Abbasoo** [comment]
What x4 ?

**Comment by Archimondee** [comment]
still waiting ar1i bot :)

**Comment by Akentrus** [comment]
Thanks for the hard and good work man! take a break u deserved it!! :D
