### ISSUE TITLE
Transfering my high cp an keeping the low 

### ISSUE THREAD

**Issue by richpiana** [Ar1i/PokemonGo-Bot#1618]
after the update the bot is transferring the high cp and keeping the low.

**Comment by BlackHatching** [comment]
Screen?

**Comment by dragonuts330** [comment]
The bot just transfer my x2 magikarp 100% IV and a 96% IV squirtle. Ive used it since ar1i has released it publicly. I set my values at transfer double pokemon true, max cp to transfer 1800cp, max iv transfer 90%. Yet it still tranfered several pokemon above 95% iv executor ect. Ive used the same settings for days and had no issues prior. Is it not calculating the IV's properly ? or is it that it checks first if duplicate and transfers before it checks iv or cp ? not sure but it does not transfer the pokemon I want reliably based on IV power.

**Comment by dragonuts330** [comment]
other than that it is working flawlessly and a big +1000000 to @Ar1i and tanks for the hard work and generosity of letting us use it.
