### ISSUE TITLE
Bug in IV calculation..

### ISSUE THREAD

**Issue by arjunvegda** [Ar1i/PokemonGo-Bot#1660]
![image](https://cloud.githubusercontent.com/assets/14841132/17464131/14119a60-5ca5-11e6-9686-1670afe1473c.png)

It says best Drowzee with 784 CP and IV is 94% but in the list it says its 75%. Which is true ?

**Comment by arjunvegda** [comment]
Another instance

![image](https://cloud.githubusercontent.com/assets/14841132/17464165/caeb0eec-5ca5-11e6-8f62-088b34550dd3.png)

**Comment by Ar1i** [comment]
You got probably more then 1 of this pokemon type?

**Comment by arjunvegda** [comment]
@Ar1i Just have 1 with the 432 CP as it says on the list.

**Comment by Ar1i** [comment]
Uhm yeah, can tell you why. Its getting there the best with CP and the best with IV :p

**Comment by emilie253** [comment]
i have had it there is 2-3 days with one eevee ;)

**Comment by arjunvegda** [comment]
@Ar1i  But why doesn't it match the pokemon on list.

**Comment by arjunvegda** [comment]
@emilie253 didn't get you.

**Comment by Ar1i** [comment]
Uhmmm probably pokemon list is not up2date?

**Comment by IIDavII** [comment]
I have a similar problem. I renamed the pokemons adding the IV % in the final of the name, for example,  I had a vaporeon with 96% IV called Vaporeon96. Now this Vaporeon in the list appears with 94%. Some pokemons have more IV and others have less than I noted.

**Comment by arjunvegda** [comment]
@Ar1i  Refreshed it twice before posting. Its still the same.

**Comment by VNRG** [comment]
ive got that same problem too, here the copy pasta from my last post:

http://puu.sh/qt5vk/dde1216834.png

System says that it has 98% (15-15-7)
but it is wrong, the actual value is 82%, which the old bot has displayed as well (have tested it recently)

with the online calculator https://pokeassistant.com/main/ivcalculator i have tested, too:

name: chansey
cp: 459
Stardust: 3500
HP:331

->IV 82.2%, and not 98% like the bot displays it currently

would be nice if that get fixed soon, otherwise the bot might transfer some pokemon for some ppl, which they didnt want
