### ISSUE TITLE
[Bug] Inventory space is being calculated incorrectly

### ISSUE THREAD

**Issue by setoy** [Ar1i/PokemonGo-Bot#177]
See the attached screenshot. 15/1000 slots, yet I've got 55 lucky eggs, 39 incense and 75 razzberrys left.
![untitled](https://cloud.githubusercontent.com/assets/6497266/17243659/43cd53ee-557e-11e6-99e9-6a44e0b630bb.png)

**Comment by TMaddox** [comment]
how the hell did you get 55 lucky eggs ?

and yeah i got this bug too

**Comment by setoy** [comment]
> (i assume your not spending money on an account where you are botting

I am and I don't care :p

**Comment by IceQ1337** [comment]
I've encountered the exact same problem. It's always showing 15 Items instead of the actual number.
It cannot be correct, because i get no items from new pokestops except for pokeballs after a catch.
![ja3ce29p](https://cloud.githubusercontent.com/assets/11349966/17247979/785eeb68-5597-11e6-91c9-c1e552338f62.png)
