### ISSUE TITLE
Add Zoom Option On The Map

### ISSUE THREAD

**Issue by DaniOurGamer** [Ar1i/PokemonGo-Bot#1839]
Hi I think it will be a good enhancement to add a buttom for the zoom on the set location. Because sometimes I use the touchpad of the laptop and I cant move quickly to the zone I want. Thanks developers

**Comment by madpada** [comment]
there is a zoom option already... its mousewheel.  You want them to add touch support?  It looks like they are using WinForms and Gestures are not supported in Windows Forms because it was feature frozen in 2005.  Its still possible to add touch support but it would be a pain.  Usually they'll add new features by request but only if enough people are asking for it.
