### ISSUE TITLE
Failed to catch Pokemon

### ISSUE THREAD

**Issue by marcop888** [Ar1i/PokemonGo-Bot#1930]
Still failed to catch pokemon but get exp from pokestop..

**Comment by PokePro21** [comment]
![12](https://cloud.githubusercontent.com/assets/20843400/17471679/9207aedc-5d63-11e6-9940-f07088a5fa05.png)

**Comment by PokePro21** [comment]
Dont keep your total count more than 330+

**Comment by PokePro21** [comment]
its just becaused u have u 0 pokeballs

**Comment by Kahjo** [comment]
Yep! Same here! https://gyazo.com/720bb81bf5a1e3e32151a700baf6e8b6

I caugh 1 pokemon from every like 5 i encounter. WTF Dooood.

**Comment by gitovahere** [comment]
TRUE, you need to set some number for regular pokeball even though you prefer to use "great" or "ultra."
It works for me after that. Before I was able to farm at pokestop but every one of the pokemon "got away." Then, tweaked some numbers and catching 1 of every 5. 

Don't put "0" in your pokeball field. Hope that helps.

**Comment by Kahjo** [comment]
Okay. So I need to have atleast one normal pokeball for it to caugh. This fixed the problem with me. Simply have some normal balls in your inventory.

**Comment by gitovahere** [comment]
Best to have at least 5 or 10 normal pokeball. What if you encounter multiple pokemons and you're out of balls between pokestops? It will try to "throw" normal pokeball even though you don't have it and that's why they kept getting away. 
Hope Ar1i will be able to fix it on the next update where we can use either great or ultra ball. Thanks a bunch!

**Comment by marcop888** [comment]
problem fixed.. Thx everyone fyi

**Comment by FGonzalezBon** [comment]
pokemon got away most time.
