### ISSUE TITLE
Evolve

### ISSUE THREAD

**Issue by icewick** [Ar1i/PokemonGo-Bot#2120]
Hello,

how dose the auto evolve work? ... do i need to catch 250 pokemon before it auto evolve or what need to happen before the auto evolve start?

thx a lot for ur great work

**Comment by BlackHatching** [comment]
it auto evolves your best pokemons  CP

**Comment by Teamozuka** [comment]
so since we are at the topic of evolving.
2 step evolutions like charmander or dratini always evolve to the second form and then obv do the same again next time 25 candies are available. is there a way to teel the bot to get me a dragonite or a charizard once in a while besides just telling it to not evolve those and i do it myself?

**Comment by xJustx** [comment]
This is only for issues. Please post your question here: https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
