### ISSUE TITLE
Pokeball value at "0" and still using it

### ISSUE THREAD

**Issue by Fertigpizza** [Ar1i/PokemonGo-Bot#2146]
I'm losing a lot of pokemon, because bot is ignoring my "0"-value for pokeballs and is still collecting/using them. Next "0"-value is going to be great balls and I think it will do the same!

**Comment by roooochi** [comment]
put it on 20.
end of disc

**Comment by Fertigpizza** [comment]
what means "end of disc"?^^
so if I put value at "20" bot wont use them?

**Comment by Experte9** [comment]
@Fertigpizza stell einfach 20 Pokebälle in deinen Settings ein und gut ist!. Ende der Diskussion.

**Comment by roooochi** [comment]
it has to use them, you have no choice, if it think it cant catch it with a nomal one it will use a better one, the great one, and so on.

**Comment by Fertigpizza** [comment]
@Experte9 
works for now... but:
so how do I prevent the bot to use them at all?
I want to get all normal pokeballs recycled and only use greater balls for now. Later in the game it should skip them too and only use ultra balls...

**Comment by AmaliaWinter** [comment]
Ich versteh gar nicht wo euer Problem liegt... der Bot fängt Pokemon mit cp von 0-499 mit Pokebällen aber 500-999 nimmt er Superbälle und ab 1000 Ultrabälle. Also lasst es einfach auf 20 Pokebälle eingestellt und fertig. Bei mir verfehlt er höchstens einen Ball von dem her.... Und so wichtig kann ein Pokemon unter 500 Cp nicht sein... Den ganzen Tag schon heulen die Leute wegen der Pokeball Issue rum...

**Comment by Fertigpizza** [comment]
so if you have like 140 greater balls and 2 pokeballs you'd rather have him use a normal pokeball for 499wp and lose it than use a greater ball and catch it?

**Comment by AmaliaWinter** [comment]
Er verliert es nicht... die Chance das er ein 499er Pokemon mit nem Pokeball verliert ist so gering das es die Diskussion nicht lohnt und selbst wenn der unwahrscheinliche Fall eintritt stirbt du davon auch nicht wenn du bei ca. 180 Pokemon die Stunde eines verlierst.... Das ist wie mit beratungsresistenten Patienten... jedes weitere Wort nutzlos

**Comment by CL0UD09** [comment]
I agree with Fertigpizza, this is a problem. There is apparently no item use logic besides the item management of what items to throw away past a certain threshold. That means that if you set pokeballs to 5, and run out, you will fail to catch the next pokemon you see below 500 CP.

This is unfortunate, because you're absolutely right: why keep using normal pokeballs when you have 50 greatballs+ and 100+ ultraballs? Why risk the chance that a 300CP 100% IV pokemon will run away? Hopefully the item use logic can be updated, or the item list config can be updated to allow you to *NOT* use normal pokeballs. Or have an option to set an IV level where it uses the max level pokeball that you have. For me, anything above 90-95% IV and I'd rather have it use an ultraball, regardless of CP.

I set it to 5, and was still missing some pokemon catches at times due to running out of normal pokeballs. For now, I would set the pokeball count to around 20 to fix this, and just deal with the few pokemon that run away because normal pokeballs were used.

**Comment by xRealMaks** [comment]
Never put a pokeball value to 0. Pokemons < 500 CP get caught with normal pokeball
