### ISSUE TITLE
offer balls

### ISSUE THREAD

**Issue by simoniuxxx147** [Ar1i/PokemonGo-Bot#2284]
could you make that if you havent pokeballs bot will use great balls? or if you havent both then ultraballs?

**Comment by xXDjMikeXx** [comment]
Yes please add a function to select wich balls should be used ore somethjing else

**Comment by gummyruler** [comment]
You will miss a lot of pokemon since pokeball has highest drop rate when it comes to stops. Great ball drops 1/3 while pokeball drops 1/2. This will cause you to lose all berries, miss a lot of pokemon, and get stuck in a loop. Since what will happen is that if u do not have pokeball it will try to catch it but you will have to flee and the pokemon is still detected on the vicinity. Which in turn the bot tries to capture again without a pokeball. You will be there for the whole eternity.

**Comment by Captnred** [comment]
Please only post issues here not suggestions. For suggestions please go here 
https://high-minded.net/threads/pokemon-go-c-bot-safer-better.50731/
Also please close this thread
