### ISSUE TITLE
Need to change the "more than 3 softban thing"

### ISSUE THREAD

**Issue by Damantium** [Ar1i/PokemonGo-Bot#2309]
It's happening with three bots on, so it needs to be changed to 2!

**Comment by gummyruler** [comment]
You can try installing VM in your PC solves the problem. Other than that it's not a problem unless you're trying to sell accounts and are on a deadline. 1 account is enough.

**Comment by Rhukz** [comment]
i have 4 times running, since when is it not possible 2 run 4 bots?

**Comment by SkyWalkerMc** [comment]
i run 3, and work correctly

**Comment by gummyruler** [comment]
@Rhukz your speed settings? I can run 3, but it's not really worth it I concentrate on one and use the other two to snipe pokemon.

**Comment by Rhukz** [comment]
i have 22 km/h and still softbanned all accounts every 3-5 minits...

**Comment by jeremie152** [comment]
wtf this update softban no stop

**Comment by Rhukz** [comment]
now i will be banned every 2-5 minits.. and i use at the moment only 1 bot... so when i use the other 3 than the problem is the same.. WHAT can i DO? u have an idea? the last days it was running without problems... maybe its 2 much? or somemone have more then 3 bots running and have an idea? thanks a lot ....  for answers :rabbit:

**Comment by Rhukz** [comment]
and right now the bots cant find pokestops :-1:  :(
