### ISSUE TITLE
Solve for all bots softban at the same time.

### ISSUE THREAD

**Issue by downspath** [Ar1i/PokemonGo-Bot#2393]
People get softbans at multiple bots at the same time, the maximum of bots you can run is 3. and you have to wayt about 1.5 minutes between activating each bot. if you activate a 4th bot you get softbaned shortly after 

(sorry for my bad english, i am german)

**Comment by AiVo7z** [comment]
Alle deine Aussagen kann ich widerlegen.

**Comment by elenex23** [comment]
How come I can only run 1 then? If i load up the 2nd i start getting ban.

**Comment by AiVo7z** [comment]
I've had 3 instances of the bot running ever since. Now Im only able to run 2 at once. Also  I've never ever waited between executing the bot. Softbans are caused by alot circumstances and also just by lagg or error of the script. Also it appears to be diffrent for each user, all I can tell they're pretty fast if you travel too fast between Locations, but softbans are too random to have a specific pattern. 
Like 6h ago I've been banned every couple tries either IP or acc even tho I only used 1 bot and 1 account.

**Comment by elenex23** [comment]
I ran all night 1 bot fine, 2 mins after loading the next bot, soft ban

**Comment by xJustx** [comment]
Not an issue
