### ISSUE TITLE
hunting in other countries

### ISSUE THREAD

**Issue by exxxplicit** [Ar1i/PokemonGo-Bot#2460]
is it possible to put your bot in other countries? i tried it once but i cant catch any pokemon and get things in poke stops,

**Comment by GundBear** [comment]
Sure can, just make sure the country you put is available for Pokemon go game, and in major city major area.

**Comment by JeCelle** [comment]
That's what we call a "softban" Niantic has put up measures to avoid pokemon trainers from "migrating" to other countries by means of using a fake gps location. That's why the bot has its own countermeasure for that in the form of "special 1337 unban method" Just wait for the bot to unban you and you're good to go. :)

**Comment by pilota56** [comment]
Push the "Force Unban" Button, you find it at the Pokemon GUI.

**Comment by GundBear** [comment]
because I locate the bot to another country, I leave to bot off for 24 hrs ( or at lease the time require to fly there from the last location).

**Comment by xJustx** [comment]
^
