### ISSUE TITLE
why always use pokeball ?

### ISSUE THREAD

**Issue by untitled02** [Ar1i/PokemonGo-Bot#2461]
How to setup not to use pokeball ?

I wanna use another sush as Ultra Ball or Great Ball in the first time to catch

**Comment by andyfeb** [comment]
Well... is it only for the first catch or for the rest of the catch process?
Maybe you can set Pokeball to 0, so the bot would throw away any of your standard PokeBall

**Comment by gummyruler** [comment]
"Bot will throw all of your pokeball if pokeball is set to 0," YES it will!! But the problem is you will be stuck in limbo without a pokeball. The bot is programmed to use pokeball for X amount of CP. Without a pokeball your character will try to catch the pokemon and will have to flee. BUT the pokemon is still there. So he will try to catch it again. It will repeat this over and over again untill the pokemon flees or expires. Just imagine that happening 10x. You will be stuck in loop for all eternity. 

And no, since pokeball drop rates are the highest on stops while great ball have lower drop rates. You will run out of great ball and it will be a huge hassle. since then again refer to the first paragraph.

**Comment by yossarianmw** [comment]
But that will make a error and all pokemon got away if u set 0..
Try it

**Comment by Experte9** [comment]
Bot catch Pokemon:
0-499 CP --> Pokeball
500-999 CP --> GeratBalls
<1000 CP --> UltraBall

**Comment by xJustx** [comment]
^
