### ISSUE TITLE
HELP I can farm pokestop but pokemon keep running away on hackbot

### ISSUE THREAD

**Issue by mckinderegg** [Ar1i/PokemonGo-Bot#2500]
I can farm pokestop but on the hackbot everytime it tries to catch a pokemon it keeps running away i have left it for like 12 hours and still the same result

**Comment by Madrocker85** [comment]
make sure you haven't ran out of pokeballs

**Comment by Kidnub** [comment]
as madrocker sayed check your pokeballs and your item config put it so that you still can grap items dont put all to high cause a basic account has just 350 items (with no extention) and only 250 pokemon places ;(
and if you try to catch a pokemon under 500cp you need a normal ball (superball untill 1000/ultra over 1000 cp ) so look that you dont have many reviever or any many tranks cause so long you run this but here you dont need any portion or any stuff of it ... cause we cannt fight on arenas if the bot is here running so for what you need portions? XD

**Comment by xRealMaks** [comment]
^

**Comment by mckinderegg** [comment]
yes thanks this thread can now be closed
