### ISSUE TITLE
PokeStop...

### ISSUE THREAD

**Issue by Personal97** [Ar1i/PokemonGo-Bot#2614]
Hello,

This morning, i'm switching on my bot and this one works during 10-15 minutes but suddenly, I see on my screen : "We can't find any Pokestop in a range of 5000m". I would know why it disps this error message on my screen.
Thanks you for yor work ;)
http://prntscr.com/c40fgo

**Comment by eNNj0y** [comment]
Same here..

reinstall don´t work.

**Comment by Tavorib** [comment]
Same as here.. Help?

**Comment by DangerousHIV** [comment]
same everyone is having this issue its very weird would love to know a fix @Personal97 @eNNj0y @Tavorib

**Comment by kazzaluis** [comment]
use hotspotshield

**Comment by xxKevinSniperxx** [comment]
hotspot shield doesn't work @kazzaluis

**Comment by DangerousHIV** [comment]
Ok so I think i found a fix that can help you Load one Bot let it go let it unbann u then turn on your hotspot shield and boom mine fixxed that way no error but if i start hotspot shield before i start the bot it gives me wackk error messages but hope this helps

**Comment by Personal97** [comment]
Thanks for answer.., an admin available ?

**Comment by xxKevinSniperxx** [comment]
@DangerousHIV what do you mean by unban? it can't unban someone if it can't access pokestops

**Comment by xxKevinSniperxx** [comment]
ok i found out that your ip has a soft ban, this usually happens when you run several bots on the same ip, you log in to your account while the bot is running, or if you use location faker too often. I'm not sure how long the ban will be but i would give it at least 3 hours or until your player is unbanned (since you'll probably be banned after using the bot, especially if you jumped locations)

**Comment by xxKevinSniperxx** [comment]
http://www.se7ensins.com/forums/threads/tutorial-ip-banned-heres-your-solution.1548353/#post-12469621

**Comment by xRealMaks** [comment]
Server slow/down. Just wait
