### ISSUE TITLE
[ pull request ] confirmation before transfer option

### ISSUE THREAD

**Issue by breketel** [Ar1i/PokemonGo-Bot#2672]
i click transfer on my 100% dragonite  because i thing the bot have confirmation before transfre .
it's my bad , but please give the confirmation button for someone else to not do that mistake again sir :) .
thx before sir .

**Comment by xuban** [comment]
This is a "pull request". Write in correct section.

**Comment by pokerave** [comment]
hahaha it said transfer of course it will transfer.. its not redundant to keep asking, its not  MS windows.

**Comment by Berk430** [comment]
is it just me or is the bot having the same problem as before? 
the thing where it doesnt find any pokestops

**Comment by breketel** [comment]
@Berk430  u got softband . close bot 10mins-30mins and open it again .
open only 1 account with 1 ip .

**Comment by breketel** [comment]
heartbreak when my 100% dragonite leave me :;(

**Comment by Berk430** [comment]
Oh ok thank you
Love the bot man u are the best

On Aug 10, 2016 10:07 PM, "breketel" <notifications@github.com> wrote:

@Berk430 <https://github.com/Berk430> u got softband . close bot
10mins-30mins and open it again .
open only 1 account with 1 ip .

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Ar1i/PokemonGo-Bot/issues/2672#issuecomment-238952379>,
or mute the thread

**Comment by breketel** [comment]
love the bot too hahaha .
me not best .
the moderator is best here :D

**Comment by pokerave** [comment]
@breketel HAHAHA 
![haha](https://cloud.githubusercontent.com/assets/20603254/17565344/bc394516-5f3f-11e6-8f7e-14ea8b502493.png)

**Comment by Berk430** [comment]
It still doesn't work
Any help?
