### ISSUE TITLE
Proxies are not working?

### ISSUE THREAD

**Issue by lucas2107** [Ar1i/PokemonGo-Bot#2741]
When i'm using proxies, the game say No pokestop found. without proxy, i can have 250 pokestop in a 10km range. I've tested with 5 differents proxy, nothing to do :/

**Comment by Ar1i** [comment]
Probably public proxys which are already in use?

**Comment by lucas2107** [comment]
Looking for french proxy, i'm going to try all of them: http://freeproxylists.net/fr/?c=FR&pt=&pr=HTTPS&a%5B%5D=0&a%5B%5D=1&a%5B%5D=2&u=0

**Comment by lucas2107** [comment]
Okey, no one is working, same problem with all:

![bebe645a18044bcfbfc91dd89f668c5f](https://cloud.githubusercontent.com/assets/11612016/17571237/b190b90e-5f4f-11e6-9d19-39a3f7467c6e.png)

**Comment by GreYzZ** [comment]
@Ar1i,
I guess I can almost confirm that.
I now tried around 10 different https proxys and none of the work

**Comment by cyb0rg01** [comment]
Well, I can't be sharing this type of issue. I just set up an simple Apache Proxy on my firms server farm. It is working for me flawlessly.

It also could be, that the Proxy Server is unstable, which is really often with public Proxies. Have you guys any experience with Proxy Servers at all? (Some of them are also using Geo Blocking)

**Comment by Ar1i** [comment]
^ this. Setup your own proxy or get a paid proxy.. free proxys these days.. kinda shit

**Comment by lucas2107** [comment]
Someone know how to setup a proxy on debian? :/ Already tried but failed xD

**Comment by cyb0rg01** [comment]
It is pretty simple while using Apache or NGiNX (just use Google). But I definitely not sharing any "How to" because you should have knowledge about using iptables / firewalld, harden your Apache Server configuration and so on.

If you don't have any knowledge about it, it is damn risk to let your own Proxy outside. (I am talking about abuses from China, Russia, USA, Japan and so on)

Just as an advice: If you are willing to do this: Configure your software or hardware firewall to be sure, that only your client (Public IP) can connect to your proxy or setup with authentication.

**Comment by Waiiim** [comment]
Sadly enought I have a VPN but the bot doesn't let me use it, if i'm not using the Proxy icon it refuses to launch the bot

**Comment by lucas2107** [comment]
Okey thanks @cyb0rg01 :+1: 

Issue Closed.
