### ISSUE TITLE
Dont use 2 bot in the same IP

### ISSUE THREAD

**Issue by k3npachi** [Ar1i/PokemonGo-Bot#2783]
I have 3 accounts

my account 1 , run since 1 hour with VPN with no probleme, account 2 and 3 with proxy are ban 

so i test launch account 2 on the same VPN of account 1 its work , but 5min after account 1 and 2 are banned 
![2016-08-11 00_52_37-](https://cloud.githubusercontent.com/assets/20956969/17573967/303d0998-5f5e-11e6-9987-d0fcef17028a.jpg)

the only solution is

-- only 1 bot launched
-- buy private proxy for dont use the same 

EDIT : while I was writing, my account with VPN no longer works either, then there are only 1 bot which works

**Comment by bboylost** [comment]
it isnt any news........ read the forum and stop posting these useless posts please

**Comment by k3npachi** [comment]
there's just so much shit that I wanted to be on the show, not to hurt

**Comment by Damantium** [comment]
So to confirm you'tr only using one bot? OR are you using two?? One normal IP and the other a proxy?

**Comment by bboylost** [comment]
Because we want to keep this 'issue ' area as clean as possible, its just any forums rule

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Aug 11, 2016 at 12:23 AM +0100, "k3npachi" <notifications@github.com<mailto:notifications@github.com>> wrote:


there's just so much shit that I wanted to be on the show, not to hurt

-

**Comment by k3npachi** [comment]
@Damantium if I use one bot that works, 2 there is a ban

with my VPN its good, i have no find good proxy for a second bot
