### ISSUE TITLE
No pokestop on bot, but works on phone?

### ISSUE THREAD

**Issue by hachihiki** [Ar1i/PokemonGo-Bot#2866]
so i used bot and it said theres no pokestop near the area (used the same coordinate and there were tons of pokestop there), so i changed IP and used proxy whatsoever nothing works. i checked pokemon go on my phone and i can see pokestops and gyms here. anyone know what happened?

**Comment by aquaeous** [comment]
i think its with the servers in populated areas, thats just my guess. im having the same issue here

**Comment by lailaps** [comment]
IP ban...

**Comment by gummyruler** [comment]
^ windows+R  > Type cmd > Enter > type ipconfig /release > ipconfig /renew. Or just restart your router.

**Comment by aquaeous** [comment]
im going to assume you were only running one bot so your ip shouldnt be banned also for the people screaming IP BAN heres a damn link for you  http://downdetector.com/status/pokemon-go

**Comment by hachihiki** [comment]
@aquaeous @gummyruler @lailaps yes i always only run one bot.. apparently i used the older version (my bad) now the bot is doing fine after i updated it..

**Comment by lailaps** [comment]
My bots are all running, with IPs around the world.
I run one bot per IP and yes, you get IP ban sometimes too, because a bot does not behave like a human! If you cannot see any Pokestops around, you have an IP ban, if you will not get anything from Pokestop and cannot catch any Pokemon you just have a softban, which can be removed by the bot!
