### ISSUE TITLE
error find pokestop

### ISSUE THREAD

**Issue by hetix** [Ar1i/PokemonGo-Bot#2874]
![sans titre](https://cloud.githubusercontent.com/assets/20968669/17586516/8ed491f6-5fc2-11e6-87ee-fad34730452b.jpg)
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by Ar1i** [comment]
IP Banned. https://github.com/Ar1i/PokemonGo-Bot/blob/master/ipbanned.md

**Comment by d4zu4x** [comment]
hetix, you has softban from server. Or maybe the server was down?? because i'm running ok from 3 hours ago.
just suggest for you, 
1. dont used wifi with ip public
2. turn off your gps on phones.
3. try again 15 minutes.
4. set walk not more from 40 km/hours on bot.
5. try unban metode.

hope can help you.
