### ISSUE TITLE
High CPs transferred

### ISSUE THREAD

**Issue by Sinan102** [Ar1i/PokemonGo-Bot#2899]
I was using v10.08 17.51 of the bot. I left my computer open about 10 hours later ( when I came back ) I realize that the bot kept lowest cps rather than highest ones. All of my pokemons are gone. Can you fix that issue ? ( I did not try last version because of this. )

**Comment by AlpaEZPZ** [comment]
its already fixed i think, i didnt see any further problems while watching the bot

**Comment by suttc1** [comment]
I for my part collect high IV's rather than high CP a discussion which took place so many times already. but it seems to be a never ending story.

configuring for HIGH CP -> Tab Pokemon =>
[ x ] Auto Transfer double Pokemons | [   ] Transfer First LowIV
Max duplicate Pokemons: 2 | Max IV to transfer 0  % | Max CP to transfer 500

I for myself like to collect high IV so I have my config like this =>
[ x ] Auto Transfer double Pokemons | [ x ] Transfer First LowIV
Max duplicate Pokemons: 0 | Max IV to transfer 90  % | Max CP to transfer 3000

**Comment by AlpaEZPZ** [comment]
this problem seems to be fixed since last update... u should close this
