### ISSUE TITLE
I know only issue but @cyberwolf888

### ISSUE THREAD

**Issue by urangotango** [Ar1i/PokemonGo-Bot#3266]
man you did brake our fucking balls shut up we know that niantic startet to make ban wafes!!! 
and what now ???? all should stop have fun with bots ??? 
just shut up go out and take an hobby little ball braker!!! 
2 of my accs got perma ban + deletation i ghive a shit on it !!! i have fun the same !!! 
im an botter and i like play with bot tools and no1 can take me this even the game creators becouse they can do what they want 1 acc banned ? ok i crate 20 new accouns ban all them to ok np i crate 100 other accounts... but read your shit spamm in any fucking issue is realy omfg idk just stop it kiddy

**Comment by urangotango** [comment]
and i say sry @xJustx @Ar1i @Logxn and all other hard workers on this project

**Comment by michaelp96x** [comment]
Bro, why are you mad?

**Comment by urangotango** [comment]
becouse ppl like this idiot make me fucking angry yust spamm shit in any issue

**Comment by Waiiim** [comment]
Without the swearing, I have to say he's right

**Comment by michaelp96x** [comment]
I agree. Before the issue section was full of bullshit. It's been cleared and still people are posting information which helps no-one. What makes it worse, no-one benefits from the thread posted.

**Comment by michaelp96x** [comment]
The OP* benefits nothing

**Comment by dstN** [comment]
and you have to open a fk...in issue for that? you know that Ar1i gets a notification for EVERY friggin issue which gets opened, which is actually EXTREMELY annoying if you try to be productive in programming. so please guys FINALLY search for your problems - and if you are 100% SURE your issue is not listed, think about the issue itself - could it be a server issue? could it be my own fault? etc etc. BEFORE posting an issue.

and to you... DON'T MAKE PERSONAL CONVERSATIONS HERE. This is GITHUB not a friggin social-media platform.

**Comment by urangotango** [comment]
man i help here and on the high mind forum more than that what you can think so dont worry i keep away a lot of stress from Ar1i and Co.
