### ISSUE TITLE
Stops Working? (NEWEST BUILD)

### ISSUE THREAD

**Issue by Hydro420** [Ar1i/PokemonGo-Bot#3386]
After a few minutes it seems the bot stops working (with newest build), seems as if it freezes for some reason? 

![untitled](https://cloud.githubusercontent.com/assets/20824888/18020125/658efa5e-6ba5-11e6-9185-9802a7f3a553.png)

**Comment by ctimevelo** [comment]
Same Issue

**Comment by Hydro420** [comment]
Waited up to 20min at one point. Only way is to re-start & it seems to freeze faster each time you do so.

**Comment by Hydro420** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20824888/18020405/dcae7046-6ba6-11e6-87d0-c1cf6719c2c2.png)

**Comment by ctimevelo** [comment]
maybe security reason??

**Comment by Hydro420** [comment]
Not sure, I would assume some type of message would appear, "camping for "x" amount of time."

**Comment by ctimevelo** [comment]
mhh ya your´e right..:X

**Comment by Hydro420** [comment]
Ill keep waiting this one out and see if it starts up again.

![untitled](https://cloud.githubusercontent.com/assets/20824888/18020753/c2b6167e-6ba8-11e6-9654-0f24c6f5d0fe.png)

**Comment by lDarkcito** [comment]
Same Issue

**Comment by Hydro420** [comment]
Started back up - caught a few pokemon & got a softban.

**Comment by EizoSik** [comment]
here you have the stable version http://sh.st/VoHDh (1.0.9.6)

**Comment by maloyah** [comment]
it is a bug , because caught pokemon return
CatchPokemonResponse.Types.CatchStatus.CatchFlee

the code in 
while (caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchMissed || caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchEscape || caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchFlee);

should be remove   caughtPokemonResponse.Status == CatchPokemonResponse.Types.CatchStatus.CatchFlee
