### ISSUE TITLE
We cant find any Pokestops, in range of 25000m!

### ISSUE THREAD

**Issue by Krypton1337** [Ar1i/PokemonGo-Bot#3400]
The Title says all! I Changed the Location and i get this Error again..

**Comment by MTK4355** [comment]
IP Ban.. Use a different proxy or if you were on your own network, were you running more than one bot at a time?

**Comment by MTK4355** [comment]
To clarify: If Niantic determines that a particular IP address is being used to host Pokémon Go bots, they blacklist the IP address and refuse to serve certain data to clients running at that specific IP. I found that using the common proxies (those listed at "hide my ass" and linked in the bot client) will quickly result in this ban because everyone else is referencing the same list. 

I use my home wifi network and run a single bot instance and never have a problem. 

@Ar1i Perfect candidate for the first wiki entry. lol

**Comment by Krypton1337** [comment]
Changed IP and it says the same Error.....

**Comment by fetmamm** [comment]
Hello. I have a suggestion for the bot, i am sorry and i know this is the wrong place to comment it on but i cant find the right place for suggestions.
So, there is a feature atm where u can tell the bot to use razz berry if the pokemon is under a certain %, and it works. But it only uses the razz berry once, so if the next throw is a miss it will not use another one. This causes it to miss ALOT of throws sometimes, and that sucks if it is using great balls. 
I suggest u to add another feature where you can tell the bot to use razz berry every time it does a throw, so if it misses the first time, it will just use another razz berry ane and try again. Do you understand what i mean?
Best regards Jesper :)

**Comment by MTK4355** [comment]
@Krypton1337 Are you using another common IP proxy? They may very well all have been banned! 

@fetmamm think about actually playing the game. If you use a raspberry, then miss the Pokémon with your pokeball, do you feed it another raspberry before trying again? 

It hurts to waste resources of any kind, but occasionally missing the pokemon is much more realistic than throwing with 100% accuracy, and it hurts more to lose your entire account. If you are worried about losing a few pokeballs, you should probably not be using a bot at all, because the odds of ultimately being banned are quite high.

**Comment by fetmamm** [comment]
oh, i thought the miss was when the pokeball hit the pokemon but didnt catch it, didnt think it was an actual miss. now i know what you mean, and you are right. wrong thought from me.
thanks for the reply anyway :)

**Comment by Krypton1337** [comment]
@MTK4355 I got IP Unbanned, it works fine!!

**Comment by MTK4355** [comment]
@Krypton1337 Sweet!

@fetmamm I thought that might be the case, but over-explained anyway. lol

**Comment by deadelf0** [comment]
latest update, farms 50xp from poke stops but doesn't give items,then works again is this intentional? fyi all balls 0?

**Comment by deadelf0** [comment]
oh, Issue was my speed, too fast.

**Comment by deadelf0** [comment]
nope, didn't fix it

**Comment by Ar1i** [comment]
Probably your inventory is full?!

**Comment by MTK4355** [comment]
I ended up running out of balls too. thought it might be programmatic only but logged in on my phone and all balls were zero! Miss rate too high?

**Comment by MTK4355** [comment]
Inventory also is not full. in my case.

**Comment by MTK4355** [comment]
The area I was farming did not have many pokestops. I'll try a spot with more and see if it restocks.

**Comment by MTK4355** [comment]
Temporarily set the bot to not catch any pokemon and I'm getting pokeballs from the pokestops. I'll let it run that way for a while to stock back up and take a look at the miss rate tomorrow.

**Comment by deadelf0** [comment]
A lot of poke stops are giving 0 items, I'd say one out of 10 give items. It's almost like the poke stops are spun and exited too quickly. Idk everything is strange in the world.

**Comment by kimjongun69** [comment]
not IP ban. soft banned. switched to another account and it worked.
