### ISSUE TITLE
Unban not working!

### ISSUE THREAD

**Issue by Craterus** [Ar1i/PokemonGo-Bot#3540]
Since today i got a Softban, maybe Niantic is doing something, idk but i can't unban me. Any Solve's for this? 

Ty Anyways!

**Comment by edale2** [comment]
softbans:

-pokemon escape when you throw pokeball: happens when you catch more than 1000 pokemon in a 23-hour period.

-can't farm pokestops: farmed more than 2000 pokestops in a 23-hour period.

There is a check about once an hour, with the oldest hour's stats dropped off as the newest hour's stats are added; so when a softban first ends, you can be just a few pokemon catches or pokestops farmed from reactivating it.

For either of these, there is no bypass, just turn the bot off for 12+ hours (I'd go 24 hours though) before using it again.

There are are few other softbans as well, mostly from things like jumping around globally and such. for those try changing your modem's external IP address (unplug it for 15 seconds, plug it back in; on some modems you can unplug the router, plug a comp in directly, wait 30 seconds, unplug computer and plug router back in).

In any case, when you have one of the two softbans I explained STOP USING THE BOT!!! Using the bot too long while softbanned can lead to a permaban.

**Comment by Zodice** [comment]
The unban option is not working anymore.
