### ISSUE TITLE
newbie here

### ISSUE THREAD

**Issue by chenrei** [Ar1i/PokemonGo-Bot#3552]
Good day everyone!

Any suggestion for good settings you have there that can run 24hr? I'm just new here ..

thanks and more power!

**Comment by fetmamm** [comment]
This is the settings that i use. I only use the bot for like 6h/day tho.
![1](https://cloud.githubusercontent.com/assets/21282959/18223942/b6388aa2-71c6-11e6-911f-aa0412cae14a.png)
![2](https://cloud.githubusercontent.com/assets/21282959/18223940/b6380b22-71c6-11e6-9f41-81ee07a1f046.png)
![3](https://cloud.githubusercontent.com/assets/21282959/18223941/b6381c98-71c6-11e6-967c-ba82ac7722b1.png)
![4](https://cloud.githubusercontent.com/assets/21282959/18223943/b6388dd6-71c6-11e6-80e8-d0ff99ff4e9d.png)

**Comment by chenrei** [comment]
thanks for the info sir. i really appreciate it. i don't have any idea what's the use of break at lure and use lure at break. not 100 percent though. ehehe gonna try it soon

**Comment by fetmamm** [comment]
I think break at lure is if you come to a pokestop with a lure on it, you will stop there for a amount of time. And lure at break is if you break at a pokestop you will put a lure there. i might be wrong

**Comment by chenrei** [comment]
ahhh thank you . might try so it later for that option.

**Comment by MTK4355** [comment]
You are correct. That's the intended use of those featues!

**Comment by MTK4355** [comment]
To clarify: if you come to a pokestop with a lure enabled and "break at lure" is enabled you will stop walking and only catch pokemon at the lure until the lure expires. 

If you want to use the "Use Lure at break" option, you need values in the "Break Interval" and "Break Length" fields or you will never actually break to use a lure! 

Note: In the current build, break times will only be respected if "Time to Run" value is set. This will be fixed in the next update though. 

I run the bot for 600 minutes per session, twice a day. 

Here are my settings:
![image](https://cloud.githubusercontent.com/assets/11677019/18227588/1a35e45a-71ef-11e6-8c03-419950c58265.png)
![image](https://cloud.githubusercontent.com/assets/11677019/18227595/38313df6-71ef-11e6-955e-89f86e48f779.png)
![image](https://cloud.githubusercontent.com/assets/11677019/18227597/4da35b7e-71ef-11e6-98cf-a832dee6afcd.png)
![image](https://cloud.githubusercontent.com/assets/11677019/18227603/8b95415e-71ef-11e6-94f6-089348c49fe9.png)

**Comment by chenrei** [comment]
Thanks @MTK4355 .. i will copy that setting of yours. good day ^_^

**Comment by Pai-GT** [comment]
I'm a newbie in GO Botting, and I would like to understand about the 'Proxies' section.
Is it necessary to set this section before stating the bot?
Thanks for your guidance in advance

**Comment by MTK4355** [comment]
Not necessary. I never use it because I always bot locally with a single bot. 

If you plan to bot in a different country, you need to use an IP from that country, and if you are going to run more than one bot at a time you need a different IP for each bot.

**Comment by MTK4355** [comment]
I'll add that my config above is a very aggressive one because the OP asked about a good 24/7 config. To play it safe I'd limit bot usage to around 4 hours per day, per account.

**Comment by Pai-GT** [comment]
Ok thanks for your comment, MTK4355
How about the API Token, should I need to config this value?
Btw, if it possible, could u share your config that not too aggressive?
:)

**Comment by MTK4355** [comment]
Only if you want to try to use telegram (Botfather) to control your bot remotely. I wasn't able to get this working well, but I haven't spent much time on it. 

On the accounts I am being super careful with I use the same config except these settings are changed:

Time to Run: 120
Break Interval: 25 (now that short breaks are fixed I'm using 28)
Break Length: 5 (^2^)

I run this config twice a day. 

BTW the most important thing you should know is that Ban risk is still quite high, don't use an account you aren't prepared to lose. 

Don't get too greedy, and know that the risk of Ban skyrockets near and above level 30.

Good Luck!

**Comment by Pai-GT** [comment]
Thanks for your kind help MTK4355
