### ISSUE TITLE
Oh,more1 question.

### ISSUE THREAD

**Issue by Jeremy2131** [Ar1i/PokemonGo-Bot#3564]
google maps routing,what is this?
How that help

**Comment by Logxn** [comment]
this is no issue.
test it

**Comment by Jeremy2131** [comment]
@Logxn i dont say what is issue,i just asking
lul

**Comment by MTK4355** [comment]
It allows the bot to use real-world paths to each pokestop, instead of moving through buildings and rivers and what have you. It's a precaution against teleporting. Just because the distance between two pokestops can be travelled at a certain speed in a straight line, does not mean that a human could actually get there in a straight line!

**Comment by Jeremy2131** [comment]
@MTK4355 i got it,ty. And more1(sry :D) i in NY now,if i want to tp Ukraine i get ban ye?

**Comment by Jeremy2131** [comment]
@MTK4355 or i can somehow avoid it?

**Comment by MTK4355** [comment]
Wait long enough to actually travel there...
