### ISSUE TITLE
Force Unban issue

### ISSUE THREAD

**Issue by erickrisnarinjaya** [Ar1i/PokemonGo-Bot#3571]
If it possible to make the bot close immediately when the bot detects softban? As we know, if we run bot when we got soft ban, it can drive us to perma ban. Because I know that the Force Unban is not working now. Plz respon, thx.

**Comment by MTK4355** [comment]
Yes. Great Idea! I'll put that in my latest pull request.

**Comment by MTK4355** [comment]
How many escaped Pokémon should trigger the Softban detect, do you think? I used 10 for now.

**Comment by erickrisnarinjaya** [comment]
Just do it pal

**Comment by Logxn** [comment]
@MTK4355 Make it a random integer from 2-10. Cuz if they miss the pokemons 10 times and then stop playing could bust us too.

and dont make it an Environment.Exit - Just disconnect from the servers, throw a message and prevent the bot from working with a random time from 30mins - 3h

**Comment by AiVo7z** [comment]
@MTK4355 don't let the bot forceclose, as logan said better let it popup an error or something, otherwise I don't know what actually caused the error. 

It would also be an improvement if the bot Counts your softbans (if you don't enable that force Close) or atleast give us a popup we Need to click. I don't know if I've ever been softbanned while Iam afk/sleeping(working. If the bot notifies us we could stop that accounts botting for a while, or/and Change Settings. thanks
