### ISSUE TITLE
Supressed error msg (Location.cs - Line 86 - Index is -1

### ISSUE THREAD

**Issue by Blubb123** [Ar1i/PokemonGo-Bot#3667]
I receive the following message every minute.
[09:58:48] [Debug] - Supressed error msg (Location.cs - Line 86 - Index is -1

**Comment by Aki86** [comment]
wait update is not rdy

**Comment by Logxn** [comment]
Yes.
I created this message.
If this message wouldnt be there it would restart the bot all the time.
I think the error message comes from @MTK4355

**Comment by MTK4355** [comment]
Nope, that one is not mine. Sorry!

**Comment by MTK4355** [comment]
I'll take a look at it though.

**Comment by Logxn** [comment]
Wooooot?
Its not yours?
Then I'll take a nother look lol

**Comment by MTK4355** [comment]
Can't seem to trigger it. Possibly errors when pokeStop has no name?

**Comment by MTK4355** [comment]
Or when it returns no items?

**Comment by Logxn** [comment]
It does not trigger for me anymore either.
I had it yesterday the whole day

(btw @MTK4355 could you get in touch with me on discord? ty :b )

**Comment by Logxn** [comment]
oh and no. It always returned items

**Comment by Blubb123** [comment]
new version works fine for me too. I close the issue. 
Great work again. thanks.

**Comment by Slayer013** [comment]
i got this same issue.. after farming for a few hours i got this message showing up after going to pokestops..
i'm not sure what triggers this error message since im not good in programming.. (sorry)

i've send this issue and closed it since i saw a similar one and i think the newest version already has no problems like this...

Thanks!
