### ISSUE TITLE
Please fix this immediately! Why this can be happen?

### ISSUE THREAD

**Issue by erickrisnarinjaya** [Ar1i/PokemonGo-Bot#3693]
![2016-09-08_083752](https://cloud.githubusercontent.com/assets/20828057/18333221/b7428592-759f-11e6-9283-267147725968.png)

I even cannot set the long or lang in the map. In the previous version, I can set this. Please fix immediately so I can use this newest bot. Thanks.

**Comment by dodogtg** [comment]
![error](https://cloud.githubusercontent.com/assets/20829256/18334364/0ef32f2a-75a1-11e6-9dcb-ed2728b85829.jpg)


error lates update download
 	Latest Build - 07.09 21.26.rar 	Reroute on Marker Click & Userwish 1.2 (#3682) 	6 hours ago

**Comment by dodogtg** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.MissingMethodException: Method not found: 'Boolean PokemonGo.RocketAPI.ISettings.get_UseBreakFields()'.
   at PokemonGo.RocketAPI.Console.GUI.GUI_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PokemonGo.RocketAPI.Console
    Assembly Version: 1.1.2.8
    Win32 Version: 1.1.2.8
    CodeBase: file:///C:/Users/it_qc/Desktop/Ar1Dev/PokemonGo.RocketAPI.Console.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1075.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Pokemon.Go.Rocket.API
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/it_qc/Desktop/Ar1Dev/Pokemon.Go.Rocket.API.DLL
----------------------------------------
POGOProtos
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/it_qc/Desktop/Ar1Dev/POGOProtos.DLL
----------------------------------------
PokemonGo.RocketAPI.Logic
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/it_qc/Desktop/Ar1Dev/PokemonGo.RocketAPI.Logic.DLL
----------------------------------------
System.Device
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Device/v4.0_4.0.0.0__b77a5c561934e089/System.Device.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by MTK4355** [comment]
Immediately huh? Sure, just kindly purchase a gold support plan from the Company Website... 

Oh wait, there isn't a support plan. There is no company. You have no right nor reason to demand or even expect support of any kind, certainly not within any specific time frame. 

Please have some respect or fix it yourself.

**Comment by erickrisnarinjaya** [comment]
just do your best shot pal thanks

**Comment by Fatal-Errol** [comment]
You disrespected the devs and your reply is "just do your best". @MTK4355 I think this guy is sending you big money without you knowing, better double check.

**Comment by erickrisnarinjaya** [comment]
Correct

**Comment by Logxn** [comment]
ffs.
for all the people with .NET error.

1. Create a new folder
2. extract the zip 
3. Go to builds only
4. Unzip
5. start exe
6. shut up and stop demanding

**Comment by ExplodingCore** [comment]
lel @Logxn 
I hope you have a macro or copy&paste those instructions >.>

**Comment by Xelwon** [comment]
XD

**Comment by Logxn** [comment]
I need them lol
