### ISSUE TITLE
Autoupdate on start doesn't work

### ISSUE THREAD

**Issue by Blubb123** [Ar1i/PokemonGo-Bot#3870]
I just started the bot  after I saw a new update of MTK4355 4 mins ago.
But the client didn't update.

**Comment by Blubb123** [comment]
Bot still sees only 1.1.4.9

**Comment by suljo94** [comment]
Because @MTK4355 didnt update the ver.md file it thinks 1.1.4.9 is the latest so it thinks that it is running the latest one just download it manualy and close this issue if the answer was satisfactory,  so in short because ver. MD  shows1.1.4.9 and you version is the same it thinks yhat it is up to date
