### ISSUE TITLE
It freezes in the initial location. I can not walk

### ISSUE THREAD

**Issue by dannyarboleda** [Ar1i/PokemonGo-Bot#3905]
It freezes in the initial location. I can not walk
![2](https://cloud.githubusercontent.com/assets/22225383/18568486/37a055ca-7b63-11e6-84cb-6ec8581a250a.PNG)

**Comment by drjack6** [comment]
I am also getting 0km/h as starting walk speed. Double checked min at 9. Happened since newest version update a few min ago

**Comment by dannyarboleda** [comment]
This error occurred since last update

**Comment by coffeexp** [comment]
Walking will take a lifetime.. it gives me a 7k+ sec to travel.. will stop botting for now until the new updates.. :) ciao!!

**Comment by Warcren** [comment]
My bot seems to have started moving again after using the new "Relocate to New Farming Location". Set Travel speed to around 10 and see if that works for you. The travel speed might be resetting to 0 due to this?
![pok](https://cloud.githubusercontent.com/assets/11487349/18569411/6728b76c-7b70-11e6-94ea-593138e4025a.PNG)

**Comment by riautama77** [comment]
the problem is when hit reload, the default walk speed reset to 0 kmh

**Comment by drjack6** [comment]
im just gonna wait for a fix
