### ISSUE TITLE
BOT does load the Pokemon-List but doesnt work...

### ISSUE THREAD

**Issue by Guiseppe3** [Ar1i/PokemonGo-Bot#3974]
The BOT loads the Pokemon-List but all he does is showing me this  (Every 60 sec. the same) :

![unbenannt](https://cloud.githubusercontent.com/assets/20943051/18644856/3d601e00-7eab-11e6-8f5c-5654fd431588.png)

**Comment by SuikasT** [comment]
same here

**Comment by jmo93** [comment]
same here

**Comment by 1celoved** [comment]
Meee tooooo! Exact same thing! The developers are so great though, I am sure they will figure it out soon

**Comment by MTK4355** [comment]
Hopefully the crashing will stop with the patch I just pushed, though I think the pokemon Transfer/Catch/Evolve lists are not loading properly now.

**Comment by kickz** [comment]
Omg, why you update something without testing ?

**Comment by 1celoved** [comment]
kickz, why are you getting so upset over something you're using for free? I mean I don't know much about you but this person is doing this for free to help us out. Everyone makes mistakes man, not everything can be always perfect. 
The update he posted after his reply is working fine for me so just re-download "The Builds"

**Comment by kickz** [comment]
Ok i understand, but if somebody want coding something so why dont give us second version of update, whick was OK ?

**Comment by Lumumba76** [comment]
Just delete complete Bot Folder and set up new with actual Version.
Had the same.

**Comment by MTK4355** [comment]
@kickz You're funny. I'll make sure the QA department goes through all of the proper steps next time...................................

You assume I pushed an update without testing it?  I did as much testing as I could afford to do myself. 

Like it or not, sometimes you guys are our test group. 

Please understand this is a passion project, and I am committed to delivering quality work because that is just what I do, but no one is perfect. Even very well funded projects are broken in updates at times, and not usually patched as quickly either. 

Sorry for the inconvenience to your botting pleasure. 

MTK
