### ISSUE TITLE
"enable pokemon sniping" can you explain?

### ISSUE THREAD

**Issue by lepriape** [Ar1i/PokemonGo-Bot#4025]
Hello , Can you explain me : "enable pokemon sniping " and "avoid region locked pokemon" .
thank you.

![capture2](https://cloud.githubusercontent.com/assets/22306773/18739227/61cebdca-80a2-11e6-8894-c05f253efc26.JPG)

**Comment by Fatal-Errol** [comment]
There are known coordinates for pokemon around the world. What this option does is it "teleports" you to those locations quickly, "clicks" on the pokemon, and return you back to your previous location before starting a capture. This method "tricks" the server that you found that pokemon in your location which makes it a little bit "safer". To avoid an obvious red flag, you should not be able to capture a pokemon that can only be seen on specific regions like Taurus, Mr.mime etc so that option is there to prevent you from capturing such pokemon. It is awesome but very risky. I suggest you do this to an account that you are not fond of.

**Comment by Fatal-Errol** [comment]
I think this explanation can be added to the bot as tool tip just to minimize people from asking frequently. Thanks to the devs for explaining it to me.

**Comment by lepriape** [comment]
thank you

**Comment by king2010116** [comment]
How to use?
If i want to catch Lapeas only

**Comment by Andrewaj** [comment]
As far as i understand its not possible to catch particular pokemon, system on start is obtaining list of all known rare pokemons and trying to catch them all, after that returns to normal boting mode.

**Comment by lepriape** [comment]
https://fastpokemap.se/
