### ISSUE TITLE
Bot disabled due to force app update

### ISSUE THREAD

**Issue by Bence98007** [Ar1i/PokemonGo-Bot#4103]
hi there!
What happened with the bot? What is that forced app update?

**Comment by pahadiboy** [comment]
forced update of pokemon go app to some higher version which do not allows rooted devices and others

**Comment by roowye** [comment]
is it available ??

**Comment by Gee3** [comment]
not anymore. pokemon go has been updated cannot be played in lower version and rooted device :(

**Comment by mquerikiol** [comment]
this is sad

**Comment by Bence98007** [comment]
Is there any update for iOS? Because I cant see any updates available.

**Comment by Gee3** [comment]
i try to bot now. you can bot again :D

**Comment by SscSPs** [comment]
Its not safe at all, not that it was at any time, but its most risky now of all times.
So I recommend not using it at all.

**Comment by Guiseppe3** [comment]
SscSPs looks like someone I would trust. Im out for now then :( 
When do you think will it be as safe as it was before ? I mean the BOT does work now, so I assume this so called API problem is solved ?! I know I´m a noob so dont hate

**Comment by Xehpo** [comment]
I posted this in the other issue, too, just want to get this out there, so you are aware:

Do NOT, under any circumstances continue to use the current version of the Bot.

Why?
-The current PokemonGo client sends encrypted data to Niantic's servers. The old clients - and the bot! - do not.
-Today Niantic forced all players with old clients to update to the current version. You cannot play, until you install the update from the app store.
-That means, everybody still playing with the old version - the one NOT sending encrypted data - is using unofficial software to play.

This is super easy for Niantic to detect. And will result in a ban. Hope that explains it a bit.

What now, you ask?
The only chance is, that the devs will crack the encryption, so that the Bot can send the same encrypted data just as the official client does. Then Niantic won't be able to spot the difference so easy any more.

Cheers everyone.

**Comment by SscSPs** [comment]
Just what @Xehpo said, only thing i would like to add is that the bot is activated for now because the a LOT of users were asking about this in the discord chat room and it looked like spam. so the devs, just to make that stop, activated the use of the bot. 
@Guiseppe3 They have not yet been able to decrypt the new encryption, some people are working on it. the new update will be posted by someone when it is available with new encryption cracked.

**Comment by edale2** [comment]
Well... I was just about ready to switch over to playing legit anyways, was hoping for another 2-300k stardust first, but should be good as-is. It's just going to be really annoying having to use an IV calculator to figure out every pokemon's IV values instead of having them listed for me...
