### ISSUE TITLE
Clearification Request

### ISSUE THREAD

**Issue by mien91** [Ar1i/PokemonGo-Bot#4107]
So please can any moderator/developer verify us if its ok to use the latest uptate on the bot program if we have updated the game in out tablets/phones?
![bot1](https://cloud.githubusercontent.com/assets/22036228/18841650/12ac5cee-841b-11e6-91b6-c07e0d5a612a.png)
FYI the message is still not prerry clear! Maybe the word   "IF" is missing?

Thanks for your time, effort and assistance!

**Comment by OldSch0ol** [comment]
I have my doubts too. Should I update the app in my phone, log in a first time in the game with new update then leave to use the bot?

**Comment by Xehpo** [comment]
Do NOT, under any circumstances continue to use the current version of the Bot.

Why?
-The current PokemonGo client sends encrypted data to Niantic's servers. The old clients - and the bot! - do not.
-Today Niantic forced all players with old clients to update to the current version. You cannot play, until you install the update from the app store.
-That means, everybody still playing with the old version - the one NOT sending encrypted data - is using unofficial software to play.

This is super easy for Niantic to detect. And will result in a ban. Hope that explains it a bit.

What now, you ask?
The only chance is, that the devs will crack the encryption, so that the Bot can send the same encrypted data just as the official client does. Then Niantic won't be able to spot the difference so easy any more.

Cheers everyone.

**Comment by SkolgeaR** [comment]
There are some things I do not understand. For example;

Yesterday I had on my iPhone version 1.5.0 (Android 0.3.5) but already existed versions 1.7 and 1.9 (0.37 and 0.39). I used bot without problem.

Today, if you want to play with the phone you have to upgrade to the latest version, ok.

BUT, if I do not upgrade, do not play with the phone, I do not touch the phone, do not use it, and I just want to use more days Bot,,,

it is not the same as to yesterday????

**Comment by MTK4355** [comment]
No, yesterday it was feasible that you were using an older version of the app to play the game. Today it is not (due to the forced update) 
If you are sending old API requests to Niantic servers YOU MUST NOT BE USING THEIR APP TO PLAY.

Clear enough now?

**Comment by SkolgeaR** [comment]
True. Absoluty clear.

**Comment by SkolgeaR** [comment]
I used bot,one hour today.
I suppose im f*cked, when i update,,,Damn.

**Comment by SkolgeaR** [comment]
*When i will update, and open the game,,,

**Comment by vitus0123456** [comment]
do you guys think pokesniper2 too risky now too?

**Comment by SkolgeaR** [comment]
So I do not lose anything if I update now and check if I'm still alive.

For though out a new Bot, I must also update. true??

**Comment by Adj1e** [comment]
Hy guys, just test using other acount. I just open my acuoun lvl 20 in newest apps and now I run bot. I hope im not get ban

**Comment by SkolgeaR** [comment]
I do same, lvl 22 run bot. Atm, no ban.
