### ISSUE TITLE
Can't find pokestops?

### ISSUE THREAD

**Issue by hubgit00** [Ar1i/PokemonGo-Bot#4132]
An error when i start to use bot anyone knows it please?

![pic](https://cloud.githubusercontent.com/assets/22661878/19155807/7ed59118-8be8-11e6-9609-99a9e774cece.png)

**Comment by inijefri** [comment]
same here ...

**Comment by Zestiria00** [comment]
Means your ip is banned

**Comment by supertrainer03** [comment]
mine too.. Niantic has installed new security measure. aside from logging in to your google account, they require actions to verify that you are not a bot, and another warning that Niantic will perma ban your account if you continue using 3rd party software, GPS spoofers, etc..

**Comment by JulioGif** [comment]
regards,

First of all excuse my English because it is not my native language and I use a translator.

I had the same problem of the speaker @hubgit00. my account is not banned can already be accessed by another device to it, I read in another post that could be the IP of the computer where you run the bot is banned, I change IP and has the same problem, something I It happens is that now ask for captacha authentication for access from the bot in future programming the bot could add a popup with the captacha of the app to be resolved.

**Comment by dodogtg** [comment]
did all bot can use anymore ?
