### ISSUE TITLE
How can your IV be valid - and % perfection too

### ISSUE THREAD

**Issue by kerkael** [Ar1i/PokemonGo-Bot#484]
Hi, anywhere  look I see that IV are to be calculated from CP and HP and Dst (and hidden Lvl).
But there are many combinations, and severa tries and/or power ups be applied to check real values.
How do you get theses specifics numbers you display immediately after capturing a pokemon ?
Do you have a different formula than 
HP = (Base Stam + Stam IV) * Lvl(CPScalar)
CP = (Base Atk + Atk IV) * (Base Def + Def IV)^0.5 * (Base Stam + Stam IV)^0.5 * Lvl(CPScalar)^2 / 10
Or even better, different values for the CPScalar found on websites ?

Thx

**Comment by FrancYescO** [comment]
The IV is intended as % perfection

 ((Attack + Defense + Stamina) / 45 ) * 100

**Comment by kerkael** [comment]
Thx FrancYescO. I know that :)
What I mean is, within the pokemongobot, each pokemon you capture is immediately completely identified : CP / HP / Dust (of course) and Att / Def / Stam IV.
My Question is : what formula is used here to get the certitude these are the correct IVs calculated ?
Or : Are the displayed IV the best possible combination ?

**Comment by FrancYescO** [comment]
these values are readed directly from the server from the bot, the real client does not show directly but use these only in fight
Thx FrancYescO. I know that :)
What I mean is, within the pokemongobot, each pokemon you capture is immediately completely identified : CP / HP / Dust (of course) and Att / Def / Stam IV.
My Question is : what formula is used here to get the certitude these are the correct IVs calculated ?
Or : Are the displayed IV the best possible combination ?

---

**Comment by kerkael** [comment]
I have to disagree. Unless you know for sure the IV values are read from the server, this is in contradiction to what I just calculated.
For what I understand now, the values shown from the bot are the AVERAGE values calculated by the formula I pasted.
I tested and powered up a few times a pokemon the bot told me it was found at 50% perfection ... where the formula told me 30-76 ... and it happened to be a 66-70% perfect IV, not a 50%.
If the IV shown here are effectively the average, it would be better to show the max possible instead.
Now, if values are read from the server ... there is something rotten in my kingdom :(

Regards

**Comment by FrancYescO** [comment]
There was a bug in the latest source version (introduced by myself when i've done the new Pokémon list and i don't know if @Ar1i fixed yet due to the tard guy)

That shows stamina and attack value equals (attack value is wrong)
I have to disagree. Unless you know for sure the IV values are read from the server, this is in contradiction to what I just calculated.
For what I understand now, the values shown from the bot are the AVERAGE values calculated by the formula I pasted.
I tested and powered up a few times a pokemon the bot told me it was found at 50% perfection ... where the formula told me 30-76 ... and it happened to be a 66-70% perfect IV, not a 50%.
If the IV shown here are effectively the average, it would be better to show the max possible instead.
Now, if values are read from the server ... there is something rotten in my kingdom :(

Regards

---
