### ISSUE TITLE
Additional functions

### ISSUE THREAD

**Issue by Ruwaa** [Ar1i/PokemonGo-Bot#520]
Hi. 
That would be great to : 
- have the possibility to chose to disable pokestop farming or disable it if inventory is full, because it only farm exp and with a small radius it doesn't catch pokemon efficienlty.
- add the radius on the map when you chose to change location.
- there is an issue when we clic on change location but finally don't change it, it does change anyway to NY default location.
- when chose location, to have the previous location shown on the map and not NY.
- have the possibility to chose options about the pokeball throw (add to many exp). chose between a great throw and a perfect etc.
- to show tips boxe which indicate what is "IV A-D-S"
- add the possibility to pause the farming

I'll add some ideas if I have more. 
By the way really nice job.
Thx a lot.

**Comment by ShutUpPvP** [comment]
there is an issue when we clic on change location but finally don't change it, it does change anyway to NY default location.

What i tried, since there was a Dragonite showing up near central park i set my speed to 300kmh and a range of 15m, click "Dont catch any pokemon" so it just goes there straight, and u should be fine and the bot is where u want him to be.

But it would still be nice if we could be able to send the bot somewhere to catch a pokemon with 300kmh, and he slows down to 10kmh, since he seems to be unable to catch the pokemon when too fast.

I think The IV A-D-S is easy to understand if ure half way interested in pokemon go and being the best.
Its Attack, Defence, Stamina for those he didnt know :)

**Comment by Ruwaa** [comment]
@ShutUpPvP Yes I know what is IV ADS but it's for thoses who don't, perhaps it's interresting to say it
