### ISSUE TITLE
[Request] Please add an always transfer option

### ISSUE THREAD

**Issue by hazmad** [Ar1i/PokemonGo-Bot#596]
This would assist with evolve XP farming.

Use example: bot evolves Pidgey, but keeps X amount of Pidgeotto. If you were to transfer all Pidgeotto's it would save space and give extra candy to evolve Pidgey

**Comment by yoyos** [comment]
It's already the case. 
After evolving task it will transfer all your evolved pokemons. 
Then, it will begin again new evolutions if candy are plenty enough

**Comment by hazmad** [comment]
Not quite. I have mine set to keep 3. bot evolves Pidgey, but keeps 3 or more (depending on CP) Pidgeotto. 

What I'm referring to is once it evolves Pidgey, to transfer all Pidgeotto. In my case I want to evolve Pidgey for the XP, then transfer Pidgeotto to get rid of it. 

Right now it doesn't transfer a Pidgeotto unless there are more than 3 under my CP transfer threshold, So I could end up with a dozen, when I'd like zero. 

I hope I've explained it properly. Thanks to everyone working on this project

**Comment by yoyos** [comment]
Yeah I understand what you mean but it's too late, this issue is closed.

@Ar1i I think hazmad wants an option to clear some pokemons no matter what, like, for example: Kakuna. You never wants it to evolve or be kept in your bag with the general rule. Maybe a select list option with pokemon you want always to be transfered could be a good idea.
