### ISSUE TITLE
[Request] Force unban at location set

### ISSUE THREAD

**Issue by DokiTeeX** [Ar1i/PokemonGo-Bot#672]
Is it possible/a good idea to force the unban at each location set ? Because when I try to catch a Dragonite precisely with Coord, that say he go away ! :(

**Comment by ShutUpPvP** [comment]
#651

**Comment by DokiTeeX** [comment]
Yeah but that will be more easy to catch rare pokemon no ? :octopus:

**Comment by ShutUpPvP** [comment]
Yes, the button to manually get unbanned is a good idea, it has been here a while ago, i think hes working on it after he fixes bugs.
but for now just set it to "not catch (dragonite or pokemon XXX) so it doesnt run away because ure banned, than when u got unbanned let it catch it again and there u go
