### ISSUE TITLE
Use Potions responsible...

### ISSUE THREAD

**Issue by CP02A** [Ar1i/PokemonGo-Bot#690]
Its not really a bug or something but wouldn't it be better when you use the items instead of deleting them?

**Comment by IceQ1337** [comment]
That does not make any sense to me to be honest. Can you explain that a bit?
Dou you mean instead of deleting your useless potions, you would like to check if there is a pokemon which is low on health to heal it instead and trash the rest? I'm pretty sure no one thought about that yet and i will check if that is even possible tomorrow.

**Comment by CP02A** [comment]
yes that was the idea what I was thinking about!
Thank you very much
and another thing, Can you make a button that uses an incense/Lucky Egg. Or better a GUI in that you can change the setting live because restarting everything again is pretty frustrating...

**Comment by IceQ1337** [comment]
I'll take a look!
