### ISSUE TITLE
encounternotfound

### ISSUE THREAD

**Issue by sargathus** [Ar1i/PokemonGo-Bot#844]
me and my friend we are getting the same problem we can't cath the pokemon becasue its says eror:encounternotfound. also i add a screenshot i hope it helps

![hata](https://cloud.githubusercontent.com/assets/20785060/17317789/06e3ef6e-5836-11e6-9250-ab039614950a.jpg)

and also there is something i dont understand exatly. first is that percentage think probaby more is the better still i couldnt figure it out 

second i wanna trasfer all pokemon under 550 cp so i put the max cp to transfer 550 but its still not transfering. sometimes it transfer but it transfer ramdomly. i lost 600 cp evee that that  was thats was my favorite pokemen.

sorry for long post and thanks in advance

**Comment by hsc2712** [comment]
Same problem here.

**Comment by Bikkstar123HD** [comment]
same issue

**Comment by guyordinary** [comment]
have same issue here

**Comment by Tracynew** [comment]
try to reload..

**Comment by Bikkstar123HD** [comment]
already did runs for a while and again error so for now al we can doi s wait for AR1 reply about it

**Comment by joeisme90** [comment]
Guys, i already try many build and the latest one has problem and not stable yet (Encounter Pokemon Fled), my advice is use the older one, i can use it without problem.

**Comment by Wi1dHunt** [comment]
Same problem here. already reload for many times and still not work

**Comment by JorgeFrancoIbanez** [comment]
this happen with the latest build, try to use the 01.08 16.59 version. All goes well.

**Comment by sargathus** [comment]
thanks guys its looks like common problem but is some pls explain that percentage thing pls?

**Comment by JorgeFrancoIbanez** [comment]
that porcentage is the individual value of your pokemon. aside of the IV you can see the attack-defense-stamina (A-D-S) values. that values say to you how good is your pokemon. For example:

If you have a zubat with CP (combat power) 173, IV 84%, Attack 11, Defense 12. Stamina 15. And in the other hand you have another Zubat with CP (combat power) 91, IV 91%, Attack 12, Defense 15. Stamina 14. I will choose the second because that one has more attack and defense, And has only 1 point below of stamina, for some stardust i will be happy with the second.

hope my english doesn`t botter you. But i hope this help you to understand. :)

**Comment by Logxn** [comment]
guys chillax. it will get fixed

**Comment by Ar1i** [comment]
#849 1 issue is enough, but i fixed it probably.
